safety_controller:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/vesc/low_level/ackermann_cmd"
    safety_topic: "/vesc/low_level/input/safety"
    side: -1
    velocity: 1.0
    desired_distance: 1.
